name: Continuous Deployment

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
        - name: Move Image
          run: cp -r backend/public ../

        - uses: actions/checkout@v2.3.3
          with:
            fetch-depth: 0
        - uses: actions/setup-node@v1.4.3
          with:
              node-version: '12.18.3'

        - name: Install dependencies
          run: |
            npm install
            npx lerna exec npm install
        - name: Create production config
          run: bash production.sh

        - name: Build production
          run: npm run build 

        - name: Restart process
          run: pm2 restart damenu