name: ci

on:
  pull_request:
    branches:
        - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2.3.3
          with:
            fetch-depth: 0

        - uses: actions/setup-node@v1.4.3
          with:
              node-version: '12.18.3'

        - name: Install dependencies
          run: |
            npm install
            npx lerna exec npm install